id: P7B03B827
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: nl
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    67893b1f950b4d01874d876e0075249f:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    e865fd8e14f443a3805b510664afcf46:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    7bc0672c31f54b18a40ebe829c48ace8:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    13c90e84b0f04460bf0839ea4d35569a:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    83ea57aeab6f449da54789f26d0984c3:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    78d8a53058b744168fae76e3a8054d11:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    6ee277dcc85341c29416992fe745b919:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    3da302a138a3449193f6fe6a15a71e59:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    ff463d77b150419284093cedfea55e7c:
      title: Prayer to Gesar
      parent: Prayers
    b52edc55e7a94b43a6bbfcabc9d6b9b4:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    0e3637f0b5dd43f2ac3384279214016a:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    e8c8b7de120548bea8818cbe802023de:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    10f31b9f3fef470e959280f1fa81eab7:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.455601'
last_modified_at: '2022-03-01T03:43:17.455604'
